### ISSUE TITLE
"More" Feature Not Working

### ISSUE THREAD

**Issue by serenap19** [bchd/bahc-ohana-api#108]
On select pages, the "more" feature is not working on the front end when I type text in the long description box on the back end. Pages include: 

COVID-19 HEALTH -- Information on Time Limits for Prescription Medications
COVID-19 DONATE/VOLUNTEER -- Red Cross
COVID-19 HEALTH -- COVID-19 Telephonic Call Lines
COVID-19 HEALTH: ShareBaby Emergency Diaper Hubs
COVID-19 MENTAL HEALTH -- Calm.com (Calm App)

Thank you!

**Comment by justuseapen** [comment]
Thank you I've added this to our backlog to check out and resolve. Will report here when we have a fix.
