### ISSUE TITLE
Search bar for "Organizations" not working

### ISSUE THREAD

**Issue by candelavazquez** [bchd/bahc-ohana-api#120]
![Screen Shot 2020-07-14 at 12 40 21 PM](https://user-images.githubusercontent.com/66443312/87452707-8b0cde80-c5cf-11ea-92b6-6e2ddf5771b2.png)
![Screen Shot 2020-07-14 at 12 40 52 PM](https://user-images.githubusercontent.com/66443312/87452709-8ba57500-c5cf-11ea-9940-015d841c2a3a.png)

The organization search bar is not currently working. When I click Organizations at the top of the page, I am not able to search for any organizations there. Additionally, when I try to create a new location, I am no able to look for organizations. Without choosing an organization, it does not allow me to create the location. Thank you for looking at this!

**Comment by danivovich** [comment]
Fixed by https://github.com/bchd/bahc-ohana-api/commit/9938c30a5669216575be82f40cf9cfe13d4a087b, deployed to all environments.
