### ISSUE TITLE
markdown for short description not working on search page

### ISSUE THREAD

**Issue by candelavazquez** [bchd/bahc-ohana-api#121]
![Screen Shot 2020-07-16 at 10 47 18 AM](https://user-images.githubusercontent.com/66443312/87686034-0bf3e380-c752-11ea-8e6e-ade9992d50d2.png)
![Screen Shot 2020-07-16 at 10 48 04 AM](https://user-images.githubusercontent.com/66443312/87686035-0c8c7a00-c752-11ea-8506-6bad399b33e7.png)

When I use the markdown features on the short description, they don't work on the search page. Thank you for looking at this!

**Comment by justuseapen** [comment]
Thank you for submitting this issue we'll triage and get it sorted.

**Comment by justuseapen** [comment]
resolved
