### ISSUE TITLE
Address details not working

### ISSUE THREAD

**Issue by candelavazquez** [bchd/bahc-ohana-api#123]
Hi! When I try to edit the address details box under a service, it does not save to the front end or the back end of charmcare. When I click "save changes & apply edits to database" it just disappears. Thank you.

**Comment by justuseapen** [comment]
Thank you for this report I will check it out shortly

**Comment by Homerade** [comment]
@candelavazquez just want to make sure, this will be showing everywhere it needs to. 

The only place I can see, is when you are on a Location page and Services are listed below the map with any information they might have.

Please let me know if there is somewhere else where it should also appear. Thanks!

**Comment by candelavazquez** [comment]
That makes sense! Thank you so much for your help.
