### ISSUE TITLE
Error message when updating

### ISSUE THREAD

**Issue by jennafitz** [bchd/bahc-ohana-api#98]
I am working to update the service titled COVID-19 Resources / COVID-19 SUBSTANCE USE TREATMENT-- Behavioral Health Leadership Institute Van. I am trying to write "Outside Baltimore Central Booking and Intake Center" in the address under street line 2. When I tried to save this, I received an error message. 
![Screen Shot 2020-06-08 at 3 24 50 PM](https://user-images.githubusercontent.com/66643330/84071766-41135600-a99c-11ea-8406-d76111d6c84e.png)
![Screen Shot 2020-06-08 at 3 24 57 PM](https://user-images.githubusercontent.com/66643330/84071773-42448300-a99c-11ea-95f7-1b48cd181187.png)

**Comment by justuseapen** [comment]
Thank you for sharing this issue I will take a look!

**Comment by justuseapen** [comment]
OK a couple things here:
1. Services don't have street addresses, locations have street addresses.
2. This is failing because our attempt to validate that location using google maps failed due to an deactivated billing account: ```Geocoder::RequestDenied (You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started):```

**Comment by jennafitz** [comment]
Hi! Thanks for getting back to me! 

My apologies- I absolutely meant location, not service. I actually just tried again, and I was able to update it as I wanted this time. Thank you!

**Comment by justuseapen** [comment]
This is resolved
