### ISSUE TITLE
Maps not working

### ISSUE THREAD

**Issue by candelavazquez** [bchd/bahc-ohana-api#99]
General maps and maps within locations have not been working recently, as shown on the screenshots. Thank you!
![Screen Shot 2020-06-09 at 12 46 18 PM](https://user-images.githubusercontent.com/66443312/84176474-6f9e3900-aa4f-11ea-8d88-4d64d45b13b8.png)
![Screen Shot 2020-06-09 at 12 46 32 PM](https://user-images.githubusercontent.com/66443312/84176477-6f9e3900-aa4f-11ea-9fee-2e5b48bd6a13.png)

**Comment by justuseapen** [comment]
This was resolved
